import Link from "next/link";
import "./globals.css";
import { Control } from "./Control.js";

export const metadata = {
   title: "WEB Tutorials",
   description: "Generated by create next app",
}; 

export default async function RootLayout({ children }) {
  const resp = await fetch('http://localhost:9999/topics', {cache : 'no-store'}); // cache : no-store는 캐쉬데이터를 사용하지않는 방법임. 더 좋은 방법은 Revaildating 하는 것
  const topics = await resp.json();
  return (
    <html>
      <body>
      <h1><Link href="/">WEB</Link></h1>
      <ol>
        {topics.map((topics)=>{
          return <li key={topics.id}><Link href={`/read/${topics.id}`}>{topics.title}</Link></li>
        })}
      </ol>
      {children}
      <Control/>
      </body>
    </html>
  );
}
